/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import javax.swing.JOptionPane;
import fatec.poo.control.DaoRecepcionista;
import fatec.poo.control.DaoRegistro;
import fatec.poo.control.DaoHospede;
import fatec.poo.control.DaoQuarto;
import fatec.poo.model.Registro;
import fatec.poo.model.Recepcionista;
import fatec.poo.model.Hospede;
import fatec.poo.model.Quarto;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author André, Rarissa e Julia
 */
public class GuiReservaLiberar extends javax.swing.JFrame {

    /**
     * Creates new form GuiReservaLiberar
     */
    public GuiReservaLiberar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtValorHospedagem = new javax.swing.JLabel();
        txtDataSaida = new javax.swing.JFormattedTextField();
        txtDataEntrada = new javax.swing.JFormattedTextField();
        txtNumQuarto = new javax.swing.JTextField();
        txtCpfHospede = new javax.swing.JFormattedTextField();
        txtRegistroFuncional = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnPesquisarRegistroFuncional = new javax.swing.JButton();
        lblPesquisaRegistroFuncional = new javax.swing.JLabel();
        btnPesquisarCpfHospede = new javax.swing.JButton();
        lblPesquisaCpfHospede = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnPesquisarSituacaoQuarto = new javax.swing.JButton();
        lblPesquisaSituacaoQuarto = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Hospedagem");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Registro Funcional");

        jLabel3.setText("CPF Hóspede");

        jLabel4.setText("N°. Quarto");

        jLabel5.setText("Data Entrada");

        jLabel6.setText("Data Saída");

        jLabel7.setText("Valor Hospedagem");

        txtValorHospedagem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        try {
            txtDataSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataSaida.setEnabled(false);

        try {
            txtDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataEntrada.setEnabled(false);

        txtNumQuarto.setEnabled(false);

        try {
            txtCpfHospede.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfHospede.setEnabled(false);

        txtRegistroFuncional.setEnabled(false);

        btnPesquisarRegistroFuncional.setText("...");
        btnPesquisarRegistroFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarRegistroFuncionalActionPerformed(evt);
            }
        });

        lblPesquisaRegistroFuncional.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnPesquisarCpfHospede.setText("...");
        btnPesquisarCpfHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarCpfHospedeActionPerformed(evt);
            }
        });

        lblPesquisaCpfHospede.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel9.setText("Situação");

        btnPesquisarSituacaoQuarto.setText("...");
        btnPesquisarSituacaoQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarSituacaoQuartoActionPerformed(evt);
            }
        });

        lblPesquisaSituacaoQuarto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.setEnabled(false);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        btnLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.setEnabled(false);
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtRegistroFuncional)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDataEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtValorHospedagem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDataSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCpfHospede)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesquisarCpfHospede)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesquisaCpfHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesquisarRegistroFuncional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesquisaRegistroFuncional, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarSituacaoQuarto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPesquisaSituacaoQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPesquisaRegistroFuncional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtRegistroFuncional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarRegistroFuncional)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCpfHospede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCpfHospede)
                    .addComponent(lblPesquisaCpfHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPesquisarSituacaoQuarto)
                        .addComponent(lblPesquisaSituacaoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorHospedagem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar)
                    .addComponent(btnLiberar)
                    .addComponent(btnSair)
                    .addComponent(btnConsultar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
            try{
                registro = new Registro(Integer.parseInt(txtCodigo.getText()), LocalDate.parse(txtDataEntrada.getText(), fmt), recepcionista);
                registro.setHospede(hospede);
                registro.setQuarto(quarto);
                registro.getQuarto().reservar();

                daoRegistro.inserir(registro);
                daoQuarto.alterar(quarto);
                
                txtCodigo.setText("");
                txtCodigo.setEnabled(false);
                txtRegistroFuncional.setText("");
                txtRegistroFuncional.setEnabled(false);
                txtCpfHospede.setText("");
                txtCpfHospede.setEnabled(false);
                txtNumQuarto.setText("");
                txtNumQuarto.setEnabled(false);
                txtDataEntrada.setText("");
                txtDataEntrada.setEnabled(false);
                lblPesquisaCpfHospede.setText("");
                lblPesquisaRegistroFuncional.setText("");
                lblPesquisaSituacaoQuarto.setText("");
                
                btnReservar.setEnabled(false);
                btnConsultar.setEnabled(true);
                txtCodigo.setEnabled(true);
                txtCodigo.requestFocus();
                                
            }catch (DateTimeParseException ex) {
                JOptionPane.showMessageDialog(null, "Data de saída inválida.", "Erro", JOptionPane.ERROR_MESSAGE);
                txtDataSaida.requestFocus();
            }
    }//GEN-LAST:event_btnReservarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        try {
            LocalDate dataSaida = LocalDate.parse(txtDataSaida.getText(), fmt);

            valorDiaria = registro.getQuarto().liberar((int) ChronoUnit.DAYS.between(registro.getDataEntrada(), dataSaida));

            txtValorHospedagem.setText(Double.toString(registro.getQuarto().getTotalFaturado()));

            btnLiberar.setEnabled(false);
            txtDataSaida.setEnabled(false);

        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(null, "Data de saída inválida.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtDataSaida.requestFocus();
        }
    }//GEN-LAST:event_btnLiberarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        registro = null;

        try {
            registro = daoRegistro.consultar(Integer.parseInt(txtCodigo.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Código inválido. Insira um valor numérico inteiro.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtCodigo.requestFocus();
            return;
        }

        if (registro == null) {//não encontrou o objeto na BD
            btnConsultar.setEnabled(false);
            txtRegistroFuncional.setEnabled(true);
            btnPesquisarRegistroFuncional.setEnabled(true);
        } else { // encontrou o objeto na BD
            // exibir atributos
            txtRegistroFuncional.setText(Integer.toString(registro.getRecepcionista().getRegFunc()));
            lblPesquisaRegistroFuncional.setText(registro.getRecepcionista().getNome());
            txtCpfHospede.setText(registro.getHospede().getCpf());
            lblPesquisaCpfHospede.setText(registro.getHospede().getNome());
            txtNumQuarto.setText(Integer.toString(registro.getQuarto().getNumero()));
            if (registro.getQuarto().getSituacao()) {
                lblPesquisaSituacaoQuarto.setText("Reservado");
            } else {
                lblPesquisaSituacaoQuarto.setText("Livre");
            }
            txtDataEntrada.setText(DateTimeFormatter.ofPattern("dd/MM/yyyy").format(registro.getDataEntrada()));

            btnConsultar.setEnabled(false);
            txtDataSaida.requestFocus();

            if (registro.getDataSaida() == null) {
                txtDataSaida.setEnabled(true);
                btnLiberar.setEnabled(true);
                txtDataSaida.requestFocus();
            }
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnPesquisarRegistroFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarRegistroFuncionalActionPerformed
        recepcionista = daoRecepcionista.consultar(Integer.parseInt(txtRegistroFuncional.getText()));

        if (recepcionista == null) { //nao achou no bd
            JOptionPane.showMessageDialog(null, "Recepcionista não cadastrado.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else { //achou no bd
            lblPesquisaRegistroFuncional.setText(recepcionista.getNome());
            
            txtRegistroFuncional.setEnabled(false);
            btnPesquisarRegistroFuncional.setEnabled(false);
            
            txtCpfHospede.setEnabled(true);
            btnPesquisarCpfHospede.setEnabled(true);
        }
    }//GEN-LAST:event_btnPesquisarRegistroFuncionalActionPerformed

    private void btnPesquisarCpfHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCpfHospedeActionPerformed
        hospede = daoHospede.consultar(txtCpfHospede.getText());

        if (hospede == null) {
            JOptionPane.showMessageDialog(null, "Hospede não cadastrado.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            lblPesquisaCpfHospede.setText(hospede.getNome());
            
            txtCpfHospede.setEnabled(false);
            btnPesquisarCpfHospede.setEnabled(false);

            txtNumQuarto.setEnabled(true);
            btnPesquisarSituacaoQuarto.setEnabled(true);
        }
    }//GEN-LAST:event_btnPesquisarCpfHospedeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("BD2211015", "BD2211015");//usuario e senha
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@192.168.1.6:1521:xe");
        daoRegistro = new DaoRegistro(conexao.conectar());
        daoHospede = new DaoHospede(conexao.conectar());
        daoRecepcionista = new DaoRecepcionista(conexao.conectar());
        daoQuarto = new DaoQuarto(conexao.conectar());
    }//GEN-LAST:event_formWindowOpened

    private void btnPesquisarSituacaoQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarSituacaoQuartoActionPerformed
        quarto = daoQuarto.consultar(Integer.parseInt(txtNumQuarto.getText()));
        
        if (quarto == null) {
            JOptionPane.showMessageDialog(null, "Quarto não cadastrado.", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean sit = quarto.getSituacao();
            if(sit){
                lblPesquisaSituacaoQuarto.setText("Ocupado");
                JOptionPane.showMessageDialog(null, "Quarto Ocupado.", "Erro", JOptionPane.ERROR_MESSAGE);
                txtNumQuarto.requestFocus();
            }
            else{
                lblPesquisaSituacaoQuarto.setText("Livre");
                
                txtNumQuarto.setEnabled(false);
                btnPesquisarSituacaoQuarto.setEnabled(false);
                
                txtDataEntrada.setEnabled(true);
                btnReservar.setEnabled(true);
            }                                
        }
    }//GEN-LAST:event_btnPesquisarSituacaoQuartoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnPesquisarCpfHospede;
    private javax.swing.JButton btnPesquisarRegistroFuncional;
    private javax.swing.JButton btnPesquisarSituacaoQuarto;
    private javax.swing.JButton btnReservar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblPesquisaCpfHospede;
    private javax.swing.JLabel lblPesquisaRegistroFuncional;
    private javax.swing.JLabel lblPesquisaSituacaoQuarto;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtCpfHospede;
    private javax.swing.JFormattedTextField txtDataEntrada;
    private javax.swing.JFormattedTextField txtDataSaida;
    private javax.swing.JTextField txtNumQuarto;
    private javax.swing.JTextField txtRegistroFuncional;
    private javax.swing.JLabel txtValorHospedagem;
    // End of variables declaration//GEN-END:variables

    private Conexao conexao = null;
    private Registro registro = null;
    private Recepcionista recepcionista = null;
    private Hospede hospede = null;
    private Quarto quarto = null;
    private DaoRecepcionista daoRecepcionista = null;
    private DaoRegistro daoRegistro = null;
    private DaoHospede daoHospede = null;
    private DaoQuarto daoQuarto = null;
    private double valorDiaria;
    private DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
}
